# Activation key pour Rocky Linux 9

# Gestionnaire de paquets
pkg_manager: dnf

# Paquets prérequis
required_packages:
  - curl
  - python3
  - chrony
vault_activation_key_field: "activation_key_rocky9"
