# Gestionnaire de paquets
pkg_manager: apt
# Paquets prérequis
required_packages:
  - curl
  - python3
  - chrony
# Nom du champ dans Vault pour cette distribution
vault_activation_key_field: "ubuntu_activation_key"
