[rocky_linux8]
#vm2 ansible_host=192.168.238.10 ansible_user=root ansible_python_interpreter=/usr/libexec/platform-python

[rocky_linux9]
vm2 ansible_host=192.168.148.131 ansible_user=root

[oracle_linux]
#vm3 ansible_host=192.168.100.186 ansible_user=root

[ubuntu_linux]
ubuntu01 ansible_host=192.168.148.129 ansible_user=root

[debian_linux12]
#vm5 ansible_host=192.168.100.184 ansible_user=root

[debian_linux13]
#vm5 ansible_host=192.168.86.128 ansible_user=root

[uyuni_server]
uyuni_srv ansible_host=192.168.148.142 ansible_user=root
