[rocky_linux]
vm2 ansible_host=192.168.100.185 ansible_user=root

[oracle_linux]
# vm3 ansible_host=192.168.100.186 ansible_user=root

[ubuntu]
vm4 ansible_host=192.168.100.188 ansible_user=root

[debian]
# vm5 ansible_host=192.168.100.188 ansible_user=root
[uyuni_server]
uyuni_srv ansible_host=192.168.78.129 ansible_user=root
