[rocky_linux8]
vm2 ansible_host=192.168.238.10 ansible_user=root
[rocky_linux9]
#vm2 ansible_host=192.168.78.138 ansible_user=root
[oracle_linux]
# vm3 ansible_host=192.168.100.186 ansible_user=root

[ubuntu_linux]
#vm4 ansible_host=192.168.100.188 ansible_user=root
[ubuntu_linux]
#vm7 ansible_host=192.168.238.100 ansible_user=root
[debian_linux12]
#vm5 ansible_host=192.168.100.184 ansible_user=root
[debian_linux13]
#vm5 ansible_host=192.168.86.128 ansible_user=root
[uyuni_server]
uyuni_srv ansible_host=192.168.238.11  ansible_user=root
